CREATE DATABASE CATALOGO;
USE CATALOGO;
CREATE TABLE CATEGORIA
(
ID INTEGER NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR (50) NOT NULL,
IDCATPERTENECE INTEGER	
);

ALTER TABLE CATEGORIA
ADD FOREIGN KEY (IDCATPERTENECE) REFERENCES CATEGORIA(ID)
ON UPDATE NO ACTION
ON DELETE NO ACTION;

DROP TABLE CATEGORIA;

CREATE TABLE PRODUCTO
(
CODIGO VARCHAR(4) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(40) NOT NULL,
PRECIO FLOAT NOT NULL,
IDCATEGORIA INTEGER NOT NULL,
FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA (ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);
 INSERT INTO CATEGORIA(ID,DESCRIPCION,IDCATPERTENECE) VALUES
(1,'CARNE',null),
(2,'CARNE ROJA',1),
(3,'CARNE DE RES',2),
(4,'CARNE DE CORDERO',2),
(5,'CARNE DE AVE',1),
(6,'CARNE DE POLLO',5),
(7,'CARNE DE PAVO',5),
(8,'BEBIDAS',null),
(9,'BEBIDAS ALCOHILICAS',8),
(10,'VINO',9),
(11,' CERVEZA',9),
(12,'BEBIDAS NO ALCOHOLICAS',8),
(13,'GASEOSA',12),
(14,'ENERGIZANTE',12),
(15,'AGUA',12),
(16,'HIGIENE PERSONAL',NULL),
(17,'CUIDADO PERSONAL',16),
(18,'JABON',17),
(19,'GEL',17);
/*TABLA DE ARBOL GENEALOGICO*/

CREATE TABLE PERSONA
(
ID INTEGER NOT NULL PRIMARY KEY,
NOMMBRE VARCHAR(50) NOT NULL,
SEXO VARCHAR(1) NOT NULL,
IDPADRE INTEGER NOT NULL,
IDMADRE INTEGER NOT NULL,
FOREIGN KEY (IDPADRE) REFERENCES PADRE (ID),
FOREIGN KEY (IDMADRE) REFERENCES MADRE (ID)
);

CREATE TABLE MADRE
(
ID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE PADRE
(
ID INTEGER NOT NULL PRIMARY KEY
);

SELECT * FROM  PERSONA;

SELECT * FROM CATEGORIA;
SELECT * FROM PRODUCTO;

SELECT CATEGORIAPADRE.ID,CATEGORIAPADRE.DESCRIPCION
FROM CATEGORIA CATEGORIAHIJO , CATEGORIA CATEGORIAPADRE
WHERE CATEGORIAHIJO.IDCATPERTENECE= CATEGORIAPADRE.ID AND
CATEGORIAHIJO.DESCRIPCION='VINO';


SELECT ID,DESCRIPCION
FROM CATEGORIA
WHERE ID IN (SELECT IDCATPERTENECE
			FROM CATEGORIA
            WHERE DESCRIPCION='VINO');
            
/*MOSTRAR LAS SUBCATEGORIAS DE LAS BEBIDAS*/

SELECT CATEGORIAHIJO.ID, CATEGORIAHIJO.DESCRIPCION
FROM CATEGORIA CATEGORIAPADRE,CATEGORIA CATEGORIAHIJO
WHERE CATEGORIAPADRE.ID=CATEGORIAHIJO.IDCATPERTENECE AND
CATEGORIAPADRE.DESCRIPCION='BEBIDAS';

/*MOSTRAR LAS SUBCATEGORIAS DE BEBIDAS NO ALCOOHOLICAS*/
SELECT *			/*SE EJECUTA PERO NO MUESTRA LO QUE NECESITO*/
FROM PRODUCTO
WHERE IDCATEGORIA IN (SELECT ID
						FROM CATEGORIA
						WHERE IDCATPERTENECE IN (SELECT ID
												FROM CATEGORIA
												WHERE DESCRIPCION='BEBIDAS NO ALCOHOLICAS'
                                                )
						);
/*MOSTRAR LA CANTIDAD DE PRODUCTO QUE EXISTEN POR CADA CATEGORIA*/

SELECT IDCATEGORIA,DESCRIPCION,COUNT(*)
FROM PRODUCTO, CATEGORIA
WHERE IDCATEGORIA=ID
GROUP BY IDCATEGORIA;

DROP DATABASE CATALOGO;