CREATE DATABASE AUTOMOTRIZ;
USE AUTOMOTRIZ;

CREATE TABLE CLIENTE
(
	CI INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(60) NOT NULL,
    TELEFONO INTEGER NOT NULL
);

CREATE TABLE VEHICULO
(
	PLACA VARCHAR(7) NOT NULL PRIMARY KEY,
    MARCA VARCHAR(30) NOT NULL,
	MODELO VARCHAR (30) NOT NULL,
    AÑO SMALLINT NOT NULL,
    COLOR VARCHAR(15) NOT NULL
);
CREATE TABLE ACCESORIO
(
	ID SMALLINT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (40) NOT NULL
);
CREATE TABLE NOTARECEPCION
(
	NRO INTEGER NOT NULL PRIMARY KEY,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    KM INTEGER NOT NULL,
    CICLIENTE INTEGER NOT NULL,
    FOREIGN KEY (CICLIENTE) REFERENCES CLIENTE (CI)
    ON UPDATE CASCADE
    ON DELETE CASCADE,      /* CAMBIA LOS DATOS ENTRE DOS CLASES PARA MANTENER LA INTEGRIDAD REFERENCIAL*/
    PLACAVEHICULO VARCHAR(7) NOT NULL,
    FOREIGN KEY (PLACAVEHICULO) REFERENCES VEHICULO (PLACA)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
/*insertar datos cliente*/
INSERT INTO CLIENTE VALUES(111,'JOAQUIN CHUMACERO',7181234);
INSERT INTO CLIENTE VALUES(222,'SATORNINO MAMANI',6193448);
INSERT INTO CLIENTE VALUES(333,'FABIOLA HERBAS',8273426);
/*INSERTAR DAOTS VEHICULOS*/

INSERT INTO VEHICULO VALUES ('SWKU300','TOYOTA','STARLET',1990,'NEGRO');
INSERT INTO VEHICULO VALUES ('STUP200','TOYOTA','IPSUM',2000,'BLANCO');
INSERT INTO VEHICULO VALUES ('KSH1333','HYUNDAI','F10',2014,'PLOMO');

/*INSERTAR DATOS A NOTA DE RECEPCION*/

INSERT INTO NOTARECEPCION VALUES (100,'2024-8-10','10:00',1000,111,'SWKU300');
INSERT INTO NOTARECEPCION VALUES (101,'2024-8-15','15:00',1500,222,'STUP200');
INSERT INTO NOTARECEPCION VALUES (102,'2024-8-20','12:00',1500,111,'STUP200');
INSERT INTO NOTARECEPCION VALUES (103,'2024-8-15','14:00',1250,333,'KSH1333');

select * from vehiculo;
select * from cliente;
select * from notarecepcion;

/* MOSTRAR KAS NOTAS DE RECEPCION DE JOAQUIN CHUMACERO*/

SELECT NOTARECEPCION.*  /*SOLO * MUESTRA LOS DATOS DEL CLIENTE*/
FROM CLIENTE, NOTARECEPCION
WHERE CI=CICLIENTE AND NOMBRE='JOAQUIN CHUMACERO';

SELECT CI
FROM CLIENTE
WHERE NOMBRE='JOAQUIN CHUMACERO';
/* MOSTRAR EL NOMBRE DE LOS CLIENTES DE TODAS LAS NOTAS DE RECEPCION*/

SELECT *
FROM NOTARECEPCION
WHERE CICLIENTE IN (SELECT CI 
					FROM CLIENTE
                    WHERE NOMBRE='JOAQUIN CHUMACERO');
                    
SELECT NRO, FECHA, HORA, CICLIENTE, NOMBRE
FROM CLIENTE, NOTARECEPCION
WHERE CI=CICLIENTE;


/*MOSTRAR QUE VEHICULO SE DEJO EN LA NOTA DE RECEPCION NRO 100*/
SELECT NRO, PLACA, MARCA, MODELO, AÑO
FROM VEHICULO,NOTARECEPCION
WHERE PLACA=PLACAVEHICULO AND NRO=100;

SELECT *
FROM VEHICULO
WHERE PLACA IN (SELECT PLACAVEHICULO
				FROM NOTARECEPCION
                WHERE NRO=100);

SELECT *
FROM CLIENTE				/*EL DISTINT ES PARA QUE NO SE REPITAN LOS CLIENTES QUE HAYAN SACADO MAS DE UNA NOTA DE RECEPCION*/
WHERE CI IN (SELECT CICLIENTE
			FROM NOTARECEPCION);

/*MOSTRAR LOS VEHICULOS QUE HA DEJADO SATURNINO MAMANI PARA ARREGLO EN EL TALLER*/

SELECT VEHICULO.*
FROM CLIENTE, NOTARECEPCION, VEHICULO 			/*LAS TABLAS QUE SE USARAN*/
WHERE CI=CICLIENTE AND PLACAVEHICULO=PLACA		/*DONDE SE RELACIONAN*/
	AND NOMBRE='SATURNINO MAMANI';				/*LO QUE SE BUSCA*/	
	
/*MOSTAR LOS CLIENTES DE LOS VEHICULOS MARACA TOYOTA*/
SELECT DISTINCT CLIENTE.*  /*PARA QUE NO SE REPITA USAMOS DISTINCT*/
FROM CLIENTE, NOTARECEPCION,VEHICULO
WHERE CI=CICLIENTE AND PLACAVEHICULO=PLACA AND MARCA='TOYOTA'; 

/*MOSTRAR LOS CLIENTES QUE AHN DEJADO SU VEHICULO ENTRE LAS 10:00 Y LAS 12:00*/

SELECT DISTINCT CLIENTE.* /*ESTA PARTE ES LA QUE MUESTRA*/
FROM CLIENTE, NOTARECEPCION
WHERE CI=CICLIENTE AND HORA='10:00' AND HORA='12:00';

SELECT DISTINCT CLIENTE.* /*ESTA PARTE ES LA QUE MUESTRA*/
FROM CLIENTE, NOTARECEPCION
WHERE CI=CICLIENTE AND HORA BETWEEN '10:00' AND '12:00';

SELECT *
FROM CLIENTE
WHERE CI IN (SELECT CICLIENTE
			FROM NOTARECEPCION
            WHERE HORA>='10:00' AND HORA<='12:00');
/*MOSTRAR LA CANTIDAD DE VEHICULOS DE LA MARCA TOYOTA*/ /*HACER PARA LA PROX CLASE */

SELECT COUNT(*)
FROM VEHICULO
WHERE MARCA='TOYOTA';

/*MOSTRAR CUANTAS VECES A DEJADO JOAQUIN CHUMACERO SU VEHICULO SWKU300*/

SELECT *
FROM CLIENTE, NOTARECEPCION
WHERE CI=CLIENTE AND PLACAVEHICULOO='SWKU300' AND NOMBRE='JOAQUIN CHUMACERO';  /*DA ERROR NO SE CUAL ES EL PROBLEMA BRAHIAN ARREGLALO PORFA*/

/*MOSTRAR LA CATIDAD DE NOTAS DE RECEPCION DE JOAQUIN CHUMACERO*/

SELECT COUNT(*)
FROM CLIENTE, NOTARECEPCION
WHERE CI=CICLIENTE AND NOMBRE='JOAQUIN CHUMACERO';

SELECT CI, NOMBRE,COUNT(NRO) AS CANTIDAD     /*  */
FROM CLIENTE,NOTARECEPCION
WHERE CI=CICLIENTE
GROUP BY CI
ORDER BY CANTIDAD DESC;
