CREATE DATABASE AUTOMOTRIZ;
USE AUTOMOTRIZ;

CREATE TABLE CLIENTE
(
	CI INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(60) NOT NULL,
    TELEFONO INTEGER NOT NULL
);

CREATE TABLE VEHICULO
(
	PLACA VARCHAR(7) NOT NULL PRIMARY KEY,
    MARCA VARCHAR(30) NOT NULL,
	MODELO VARCHAR (30) NOT NULL,
    AÑO SMALLINT NOT NULL,
    COOR VARCHAR(15) NOT NULL
);
CREATE TABLE ACCESORIO
(
	ID SMALLINT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (40) NOT NULL
);
CREATE TABLE NOTARECEPCION
(
	NRO INTEGER NOT NULL PRIMARY KEY,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    KM INTEGER NOT NULL,
    CICLIENTE INTEGER NOT NULL,
    FOREIGN KEY (CICLIENTE) REFERENCES CLIENTE (CI)
    ON UPDATE CASCADE
    ON DELETE CASCADE,      /* CAMBIA LOS DATOS ENTRE DOS CLASES PARA MANTENER LA INTEGRIDAD REFERENCIAL*/
    PLACAVE VARCHAR(7) NOT NULL,
    FOREIGN KEY (PLACAVE) REFERENCES VEHICULO (PLACA)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
/*insertar datos cliente*/
INSERT INTO CLIENTE VALUES(111,'JOAQUIN CHUMACERO',7181234);
INSERT INTO CLIENTE VALUES(222,'SATORNINO MAMANI',6193448);
INSERT INTO CLIENTE VALUES(333,'FABIOLA HERBAS',8273426);
/*INSERTAR DAOTS VEHICULOS*/

INSERT INTO VEHICULO VALUES ('SWKU300','TOYOTA','STARLET',1990,'NEGRO');
INSERT INTO VEHICULO VALUES ('STUP200','TOYOTA','IPSUM',2000,'BLANCO');
INSERT INTO VEHICULO VALUES ('KSH1333','HYUNDAI','F10',2014,'PLOMO');

/*INSERTAR DATOS A NOTA DE RECEPCION*/

INSERT INTO NOTARECEPCION VALUES (100,'2024-8-10','10:00',1000,111,'SWKU300');
INSERT INTO NOTARECEPCION VALUES (101,'2024-8-15','15:00',1500,222,'STUP200');
INSERT INTO NOTARECEPCION VALUES (102,'2024-8-20','12:00',1500,111,'STUP200');
INSERT INTO NOTARECEPCION VALUES (103,'2024-8-15','14:00',1250,333,'KSH1333');
